config/routes.rb
UAR2::Application.routes.draw do
    resources :studies do
      resources :reports
    end

  
  root :to => 'studies#index'
  
  match "/auth/twitter/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :study
end

app/models/study.rb
class Study < ActiveRecord::Base
  
  has_many :reports
end

app/models/user.rb
class User < ActiveRecord::Base
  
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.xml
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.xml
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.xml
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @study = Study.find(params[:study_id])
    @report = @study.reports.find(params[:id])
  end

  # POST /reports
  # POST /reports.xml
  def create
    @study = Study.find(params[:study_id])
    @report = @study.reports.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to(@study, :notice => 'Report was successfully created.') }
        format.xml  { render :xml => @report, :status => :created, :location => @report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.xml
  def update
    @study = Study.find(params[:study_id])
    @report = @study.reports.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to(@study, :notice => 'Report was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.xml
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to(study_path(@report.study_id)) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
  
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  # GET /studies
  # GET /studies.xml
  def index
    @studies = Study.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @studies }
    end
  end

  # GET /studies/1
  # GET /studies/1.xml
  def show
    @study = Study.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @study }
    end
  end

  # GET /studies/new
  # GET /studies/new.xml
  def new
    @study = Study.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @study }
    end
  end

  # GET /studies/1/edit
  def edit
    @study = Study.find(params[:id])
  end

  # POST /studies
  # POST /studies.xml
  def create
    @study = Study.new(params[:study])

    respond_to do |format|
      if @study.save
        format.html { redirect_to(@study, :notice => 'Study was successfully created.') }
        format.xml  { render :xml => @study, :status => :created, :location => @study }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @study.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /studies/1
  # PUT /studies/1.xml
  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(params[:study])
        format.html { redirect_to(@study, :notice => 'Study was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @study.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.xml
  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      format.html { redirect_to(studies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UAR2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/_form.html.erb
<%= form_for [@study, @report] do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @study_report %> |
<%= link_to 'Back', study_report_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Study</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.title %></td>
    <td><%= report.body %></td>
    <td><%= report.study %></td>
    <td><%= link_to 'Show', report %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Destroy', report, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', study_reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @report.title %>
</p>

<p>
  <b>Body:</b>
  <%= @report.body %>
</p>

<p>
  <b>Study:</b>
  <%= @report.study %>
</p>


<%= link_to 'Edit', edit_study_report_path(@report.study_id, @report) %> |
<%= link_to 'Back', study_path(@report.study_id) %>

app/views/studies/_form.html.erb
<%= form_for(@study) do |f| %>
  <% if @study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
      <% @study.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing study</h1>

<%= render 'form' %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<h1>Listing studies</h1>

<% if current_user %>
  Welcome <%= current_user.name  %>! with id: <%= current_user.uid  %>
  <%= link_to "Sign Out", signout_path %>
<% else %>
  <%= link_to "Sign in with Twitter", "/auth/twitter" %>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>User:</th>
    <th></th>
    <th></th>
  </tr>

<% @studies.each do |study| %>

  <tr>
    <td><%= study.name %></td>
	<td><%= study.user %></td>
    <td><%= link_to 'Show', study %></td>
    <td><%= link_to 'Edit', edit_study_path(study) %></td>
    <td><%= link_to 'Destroy', study, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Study', new_study_path %>

app/views/studies/new.html.erb
<h1>New study</h1>

<%= render 'form' %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @study.name %>
</p>
<p>
  <b>User:</b>
  <%= @study.user %>
</p>

<h1>Listing reports</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @study.reports.each do |report| %>
  <tr>
    <td><%= report.title %></td>
    <td><%= report.body %></td>
    <td><%= link_to 'Show', study_report_path(report.study_id, report) %></td>
    <td><%= link_to 'Edit', edit_study_report_path(report.study_id, report) %></td>
    <td><%= link_to 'Destroy', [report.study, report], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<h2>Add a report:</h2>
<%= form_for([@study, @study.reports.build]) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>